name: test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.3'
          - '1.4'
          - 'nightly'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          DISABLE_AMEND_COVERAGE_FROM_SRC: yes
      - uses: julia-actions/julia-format@master
